'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Platformer_with_Level_Editor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property level() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("level", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1,0,832,2000,64,&quot;Block&quot;,#FALSE#,1,1088,576,64,64,&quot;Block&quot;,#FALSE#,1,1344,576,320,64,&quot;Block&quot;,#FALSE#,1,1472,320,64,64,&quot;Block&quot;,#FALSE#,1,256,320,192,192,&quot;Block&quot;,#FALSE#,1,512,448,64,64,&quot;Block&quot;,#FALSE#,2,1088,320,64,64,&quot;Bill&quot;,#FALSE#,2,1472,64,64,64,&quot;Bill&quot;,#FALSE#,3,768,768,320,64,&quot;Bush&quot;,#FALSE#,3,1600,768,64,64,&quot;Bush&quot;,#FALSE#,4,512,64,192,128,&quot;Cloud&quot;,#FALSE#,4,1728,64,128,64,&quot;Cloud&quot;,#FALSE#,.
        '''</summary>
        Friend ReadOnly Property TESTFILE() As String
            Get
                Return ResourceManager.GetString("TESTFILE", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
