'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Platformer_with_Level_Editor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property CashCollected() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CashCollected", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property clear() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("clear", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0,0,0,14336,2624,0,0,0,0,-7876885,&quot;Level&quot;,7,128,768,64,64,0,0,0,0,-47872,&quot;Spawn&quot;,1,0,832,576,576,0,0,0,0,-47872,&quot;Block&quot;,1,1152,576,64,64,0,0,0,0,-47872,&quot;Block&quot;,1,1472,576,320,64,0,0,0,0,-47872,&quot;Block&quot;,1,1600,320,64,64,0,0,0,0,-47872,&quot;Block&quot;,1,2048,704,128,704,0,0,0,0,-47872,&quot;Block&quot;,1,2752,640,128,768,0,0,0,0,-47872,&quot;Block&quot;,1,3328,576,128,1024,0,0,0,0,-47872,&quot;Block&quot;,1,4096,576,64,1024,0,0,0,0,-47872,&quot;Block&quot;,1,4608,576,64,64,0,0,0,0,-47872,&quot;Block&quot;,1,5568,576,192,64,0,0,0,0,-47872,&quot;Block&quot;,1,5760,320,576,64,0,0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Demo10() As String
            Get
                Return ResourceManager.GetString("Demo10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0,0,0,14336,2624,0,0,0,0,-7876885,&quot;Level&quot;,7,128,768,64,64,0,0,0,0,-47872,&quot;Spawn&quot;,1,0,832,576,576,0,0,0,0,-47872,&quot;Block&quot;,1,1152,576,64,64,0,0,0,0,-47872,&quot;Block&quot;,1,1472,576,320,64,0,0,0,0,-47872,&quot;Block&quot;,1,1600,320,64,64,0,0,0,0,-47872,&quot;Block&quot;,1,2048,704,128,704,0,0,0,0,-47872,&quot;Block&quot;,1,2752,640,128,1984,0,0,0,0,-47872,&quot;Block&quot;,1,3328,576,128,1088,0,0,0,0,-47872,&quot;Block&quot;,1,4096,576,64,1088,0,0,0,0,-47872,&quot;Block&quot;,1,4608,576,64,64,0,0,0,0,-47872,&quot;Block&quot;,1,5568,576,192,64,0,0,0,0,-47872,&quot;Block&quot;,1,5760,320,576,64,0, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Demo14() As String
            Get
                Return ResourceManager.GetString("Demo14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0,0,0,14336,2624,0,0,0,0,-7876885,&quot;Level&quot;,7,128,768,64,64,0,0,0,0,-47872,&quot;Spawn&quot;,1,0,832,576,576,0,0,0,0,-47872,&quot;Block&quot;,1,1152,576,64,64,0,0,0,0,-47872,&quot;Block&quot;,1,1472,576,320,64,0,0,0,0,-47872,&quot;Block&quot;,1,1600,320,64,64,0,0,0,0,-47872,&quot;Block&quot;,1,2048,704,128,704,0,0,0,0,-47872,&quot;Block&quot;,1,2752,640,128,1984,0,0,0,0,-47872,&quot;Block&quot;,1,3328,576,128,1088,0,0,0,0,-47872,&quot;Block&quot;,1,4096,576,64,1088,0,0,0,0,-47872,&quot;Block&quot;,1,4608,576,64,64,0,0,0,0,-47872,&quot;Block&quot;,1,5568,576,192,64,0,0,0,0,-47872,&quot;Block&quot;,1,5760,320,576,64,0, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Demo15() As String
            Get
                Return ResourceManager.GetString("Demo15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property eliminated() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("eliminated", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property level() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("level", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Portal() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Portal", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
